SET SEARCH_PATH = "I_OPE";
DROP TABLE IF EXISTS "TB_DETAIL_VENTE" ;
DROP TABLE IF EXISTS "TB_VENTE" ;
DROP TABLE IF EXISTS "TB_PRODUIT" ;
DROP TABLE IF EXISTS "TB_SOUS_CATEGORIE" ;
DROP TABLE "TB_CATEGORIE";
DROP TABLE IF EXISTS "TB_CLIENT" ;
DROP TABLE IF EXISTS "TB_TYPE_CLIENT" ;