SET SEARCH_PATH = "I_OPE";


DROP TABLE IF EXISTS "TB_TYPE_CLIENT" ;
CREATE TABLE "TB_TYPE_CLIENT" 
(
"CD_TYPE_CLIENT" VARCHAR(50) NOT NULL,
"LB_TYPE_CLIENT" VARCHAR(100) NOT NULL,
CONSTRAINT "TB_TYPE_CLIENT_PKEY" PRIMARY KEY("CD_TYPE_CLIENT")
);


DROP TABLE IF EXISTS "TB_CLIENT" ;
CREATE TABLE "TB_CLIENT" 
(
"ID_CLIENT" VARCHAR(50) NOT NULL,
"NOM_CLIENT" VARCHAR(100) NOT NULL,
"PREN_CLIENT" VARCHAR(100) NOT NULL,
"CD_POSTAL_CLIENT" VARCHAR(100) NOT NULL,
"VILLE_CLIENT" VARCHAR(100) NOT NULL,
"PAYS_CLIENT" VARCHAR(100) NOT NULL,
"REGION_CLIENT" VARCHAR(100) NOT NULL,
"CD_TYPE_CLIENT" VARCHAR(50) NOT NULL,
CONSTRAINT "TB_CLIENT_PKEY" PRIMARY KEY("ID_CLIENT"),
CONSTRAINT "TB_CLIENT_FKEY" FOREIGN KEY ("CD_TYPE_CLIENT") REFERENCES "TB_TYPE_CLIENT"("CD_TYPE_CLIENT")
);


DROP TABLE IF EXISTS "TB_CATEGORIE";
CREATE TABLE "TB_CATEGORIE" 
(
"CD_CATEGORIE" VARCHAR(50) NOT NULL,
"LB_CATEGORIE" VARCHAR(100) NOT NULL,
CONSTRAINT "TB_CATEGORIE_PKEY" PRIMARY KEY("CD_CATEGORIE")
);


DROP TABLE IF EXISTS "TB_SOUS_CATEGORIE" ;
CREATE TABLE "TB_SOUS_CATEGORIE" 
(
"CD_SOUS_CATEGORIE" VARCHAR(50) NOT NULL,
"LB_SOUS_CATEGORIE" VARCHAR(100) NOT NULL,
"CD_CATEGORIE" VARCHAR(100) NOT NULL,
CONSTRAINT "TB_SOUS_CATEGORIE_PKEY" PRIMARY KEY("CD_SOUS_CATEGORIE"), 											
CONSTRAINT "TB_CATEGORIE_FKEY" FOREIGN KEY ("CD_CATEGORIE") 
	REFERENCES "TB_CATEGORIE"("CD_CATEGORIE")
);


DROP TABLE IF EXISTS "TB_PRODUIT" ;
CREATE TABLE "TB_PRODUIT" 
(
"CD_PRODUIT" VARCHAR(50) NOT NULL,
"NOM_PRODUIT" VARCHAR(100) NOT NULL,
"PRIX_ACHAT_PRODUIT" NUMERIC NOT NULL,
"PRIX_VENTE_PRODUIT" NUMERIC NOT NULL,
"CD_SOUS_CATEGORIE" VARCHAR(50) NOT NULL,
CONSTRAINT "TB_PRODUIT_PKEY" PRIMARY KEY("CD_PRODUIT"), 											
CONSTRAINT "TB_PRODUIT_FKEY" FOREIGN KEY ("CD_SOUS_CATEGORIE") 
	REFERENCES "TB_SOUS_CATEGORIE"("CD_SOUS_CATEGORIE")
);


DROP TABLE IF EXISTS "TB_VENTE" ;
CREATE TABLE "TB_VENTE" 
(
"ID_VENTE" VARCHAR(50) NOT NULL,
"DT_VENTE" TIMESTAMP NOT NULL,
"ID_CLIENT" VARCHAR(50) NOT NULL,
CONSTRAINT "TB_VENTE_PKEY" PRIMARY KEY("ID_VENTE"), 											
CONSTRAINT "TB_VENTE_FKEY" FOREIGN KEY ("ID_CLIENT") 
	REFERENCES "TB_CLIENT"("ID_CLIENT")
);


DROP TABLE IF EXISTS "TB_DETAIL_VENTE" ;
CREATE TABLE "TB_DETAIL_VENTE" 
(
"ID_VENTE" VARCHAR(50) NOT NULL,
"CD_PRODUIT" VARCHAR(50) NOT NULL,	
"QTE_VENTE" NUMERIC NOT NULL,
	"PRIX_VENTE" NUMERIC NOT NULL,
	"PRIX_ACHAT" NUMERIC NOT NULL,
CONSTRAINT "TB_DETAIL_VENTE_PKEY" PRIMARY KEY("ID_VENTE","CD_PRODUIT"), 											
CONSTRAINT "TB_VENTE_DETAIL_VTE_FKEY" FOREIGN KEY ("ID_VENTE") 
	REFERENCES "TB_VENTE"("ID_VENTE"), 
CONSTRAINT "TB_VENTE_DETAIL_PRODUIT_FKEY" FOREIGN KEY ("CD_PRODUIT") 
	REFERENCES "TB_PRODUIT"("CD_PRODUIT")
);